== Preamble

=== Abstract

[NOTE]
This model was adopted by ICSM's Address Working Group in June 2024 as the national model for address information in Australia. Various State/Territory agencies are working to implement the model in their respective jurisdictions.

A Semantic Web data model of address information that caters specifically for Australian & New Zealand's address modelling needs.

This model was originally developed between 2021 and 2023 for Queensland Spatial Information, a unit of Queensland's then Department of Resources, to assist with their future address database design. It is informed by the ICSM's Addressing 2035: Addressing Reform and Innovation for Australia and New Zealand, published in late 2021, which listed 'pain points' with current ANZ address models and considered future address modelling needs. This model tries to address the 10 main Requirements established by the Strategy. This model is also informed by both the relational database model used for the G-NAF, Australia's Geocoded National Address File, and CSIRO work in 2018 to characterise the GNAF in Semantic Web form, the ontology for which is online at https://linked.data.gov.au/def/gnaf, as well as the ISO's ISO19160-1 Addressing Part 1: Conceptual model. In 2023, several parts of this model covering general modelling issues, such as lifecycle representation, were extracted out into a series of mini-models to allow other models to reuse them without importing this model. As a result, the 2023 version fo this model appears to be greatly reduced in complexity and coverage but coverage is unchanged with those mini-models are also used.

=== Namespaces

This model is built on a small set of well-regarded Semantic Web models which use a variety of namespaces. Additionally, this model is expected to be used with a series of mini-models which were created alongside it and they also used namespaces. Prefixes for these namespaces, used throughout this document, are listed below.

[width=100%, frame=none, grid=none, cols="1,4,5"]
|===
|Prefix | Namespace | Description

| `*addr*` | `*https://linked.data.gov.au/def/addr/*` | *This model*
| `als` | `https://linked.data.gov.au/def/address-lifecycle-stage-type/` | Address Lifecycle Stage Types vocabulary
| `apt` | `https://linked.data.gov.au/def/address-part-type/` | Address Part Types vocabulary
| `asgsed3` | `https://linked.data.gov.au/dataset/asgsed3` | Australian Statistical Geographies Standard Dataset, Release 3
| `cn` | `https://linked.data.gov.au/def/cn/` | Compound Naming Model
| `ex` | `http://example.com/` | Generic examples
| `geo` | `http://www.opengis.net/ont/geosparql#` | OGC GeoSPARQL
| `gt` | `http://www.opengis.net/ont/geocode-types/` | Geocode types vocabulary
| `ls` | `https://linked.data.gov.au/def/lifecycle/` | Lifecycle Model
| `owl` | `http://www.w3.org/2002/07/owl#` | Web Ontology Language ontology
| `rdf` | `http://www.w3.org/1999/02/22-rdf-syntax-ns#` | The RDF Concepts Vocabulary
| `rdfs` | `http://www.w3.org/2000/01/rdf-schema#` | RDF Schema ontology
| `sosa` | `http://www.w3.org/ns/sosa/` | Sensor, Observation, Sample, and Actuator ontology
| `schema` | `https://schema.org/` | schema.org model
| `skos` | `http://www.w3.org/2004/02/skos/core#` | Simple Knowledge Organization System (SKOS) ontology
| `time` | `http://www.w3.org/2006/time#` | Time Ontology in OWL
| `void` | `http://rdfs.org/ns/void#` | Vocabulary of Interlinked Data (VoID) ontology
| `xsd` | `http://www.w3.org/2001/XMLSchema#` | XML Schema Definitions ontology
|===

=== Conformance

This model's specification conforms to the https://w3id.org/profile/ontpub[OntPub Profile] which is a standard for ontology publication that mandates certain structural and metadata properties for the model as a whole and model elements.

==== Figures

Figures used in this document use the following key:

[[fig-figure-key]]
.Key of elements used in this Model's figures
image::img/Key.svg[]

==== Example Data

Example data used in this document, for instance in model element "Example" values, are <<RDF>> data presented in the <<TTL>> syntax.