[[AnnexB]]
== Annex B: Validation

This model is a conceptual model for addressing (see <<Address part templating>> for model type details) and implementers of it are expected to create validators for use with it that test data according to their business rules. Implementers may, for example, test to see whether their data uses particular values for particular vocabularies or that geocodes are within a certain distance of the boundary of the Addressable Object.

The validation system proposed for use with this model is the _Shapes Constraint Language (SHACL)_ <<SHACL>> which implements validators for <<RDF>> data.

=== B.1 Provided Validators

Two example validators are provided with this model:

. https://github.com/icsm-au/addr-model/blob/main/validator.ttl[validator.ttl] - a canonical validator for this model
.. Test that every Address indicates: an Addressable Object with `cn:isNameFor`; a Geocode with `addr:hasGeocode`; at least one part, that is a Compound Name, with `schema:hasPart` etc
. https://github.com/icsm-au/addr-model/blob/main/validator-qld.ttl[validator-qld.ttl] a validator for a jurisdiction - Queensland
.. Tests that every Address indicates at least 3 parts - just for demonstration

=== B.2 Performing validation

The validators given above may be applied to RDF data implementations of this model using any one of a number of tools such as any in this list:

* https://pypi.org/project/pyshacl/[pySHACL]
** free and open source Python SHACL validator
* https://shacl.org/playground/[SHACL Playground]
** online Javascript-based validator
* https://tools.kurrawong.ai/validate[KurrawongAI's Validator]
** online pySHACL-based validator
** preloaded with these validators

=== B.3 Example Validation data

See the example data for <<Address>> class. A copy of it is also stored in this model's version control repository as well as an extended example that contains all the additions needed to be valid accordin to the canonical validator. See

* [Extended Example > Address Class E.G.](https://github.com/icsm-au/addr-model/tree/main/extended-examples)
